docker: Update to Bioconductor 3.10
This fixes the R packages installation error

```
Error: To use Bioconductor version '3.9', first downgrade 8 packages with
    BiocManager::install(version = '3.9')
```